<!DOCTYPE html>
<html>
    <head>
    <link rel="stylesheet" href="java.css" type="text/css">
    </head>
    <body>
        <script>
            function maquillaje(){
            var container = document.getElementById("contenedor");
            container.innerHTML = "<table class='t' align='center' style='position: relative;'><tr class='tr'><th><button onclick='none'>&nbsp;Pitbulls&nbsp;</button></th></tr><tr><th><span>/ MAQUILLAJE /</span></th></tr><tr class='tr1'><td><div class='registrar'><form method='POST' autocomplete='off' align='center'><button class='mostrarin'></button><input type='text' name='nombremaqui' placeholder='ingrese el nombre del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='srcmaqui' placeholder='ingrese el src del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='number' name='preciomaqui' placeholder='ingrese el precio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='descripcionmaqui' placeholder='ingrese la descripcion' align='center' class='textin' required><button class='mostrarin'></button><br><input type='submit' class='iniciarad' value='registrar' name='registrarmaqui'><input type='reset' class='resetad'></form><br>&nbsp;</td></tr></table>";
            }
            function figuras(){
            var container = document.getElementById("contenedor");
            container.innerHTML = "<table class='t' align='center' style='position: relative;'><tr class='tr'><th><button onclick='none'>&nbsp;Pitbulls&nbsp;</button></th></tr><tr><th><span>/ FIGURAS /</span></th></tr><tr class='tr1'><td><div class='registrar'><form method='POST' autocomplete='off'  align='center'><button class='mostrarin'></button><input type='text' name='nombrefigu' placeholder='ingrese el nombre del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='srcfigu' placeholder='ingrese el src del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='number' name='preciofigu' placeholder='ingrese el precio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='descripcionfigu' placeholder='ingrese la descripcion' align='center' class='textin' required><button class='mostrarin'></button><br><input type='submit' class='iniciarad' value='registrar' name='registrarfigu'><input type='reset' class='resetad'></form><br>&nbsp;</td></tr></table>";
            }
            function tecnologia(){
            var container = document.getElementById("contenedor");
            container.innerHTML = "<table class='t' align='center' style='position: relative;'><tr class='tr'><th><button onclick='none'>&nbsp;Pitbulls&nbsp;</button></th></tr><tr><th><span>/ TECNOLOGIA /</span></th></tr><tr class='tr1'><td><div class='registrar'><form method='POST' autocomplete='off'  align='center'><button class='mostrarin'></button><input type='text' name='nombretec' placeholder='ingrese el nombre del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='srctec' placeholder='ingrese el src del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='number' name='preciotec' placeholder='ingrese el precio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='descripciontec' placeholder='ingrese la descripcion' align='center' class='textin' required><button class='mostrarin'></button><br><input type='submit' class='iniciarad' value='registrar' name='registrartec'><input type='reset' class='resetad'></form><br>&nbsp;</td></tr></table>";
            }
            function mangas(){
            var container = document.getElementById("contenedor");
            container.innerHTML = "<table class='t' align='center' style='position: relative;'><tr class='tr'><th><button onclick='none'>&nbsp;Pitbulls&nbsp;</button></th></tr><tr><th><span>/ MANGAS /</span></th></tr><tr class='tr1'><td><div class='registrar'><form method='POST' autocomplete='off'  align='center'><button class='mostrarin'></button><input type='text' name='nombremanga' placeholder='ingrese el nombre del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='srcmanga' placeholder='ingrese el src del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='number' name='preciomanga' placeholder='ingrese el precio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='descripcionmanga' placeholder='ingrese la descripcion' align='center' class='textin' required><button class='mostrarin'></button><br><input type='submit' class='iniciarad' value='registrar' name='registrarmanga'><input type='reset' class='resetad'></form><br>&nbsp;</td></tr></table>";
            }
            function deportes(){
            var container = document.getElementById("contenedor");
            container.innerHTML = "<table class='t' align='center' style='position: relative;'><tr class='tr'><th><button onclick='none'>&nbsp;Pitbulls&nbsp;</button></th></tr><tr><th><span>/ Deportes /</span></th></tr><tr class='tr1'><td><div class='registrar'><form method='POST' autocomplete='off'  align='center'><button class='mostrarin'></button><input type='text' name='nombredep' placeholder='ingrese el nombre del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='srcdep' placeholder='ingrese el src del producto' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='number' name='preciodep' placeholder='ingrese el precio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='descripciondep' placeholder='ingrese la descripcion' align='center' class='textin' required><button class='mostrarin'></button><br><input type='submit' class='iniciarad' value='registrar' name='registrardep'><input type='reset' class='resetad'></form><br>&nbsp;</td></tr></table>";
            }
            function anuncios(){
            var container = document.getElementById("contenedor");
            container.innerHTML = "<table class='t' align='center' style='position: relative;'><tr class='tr'><th><button onclick='none'>&nbsp;Pitbulls&nbsp;</button></th></tr><tr><th><span>/ ANUNCIOS /</span></th></tr><tr class='tr1'><td><div class='registrar'><form method='POST'autocomplete='off'   align='center'><button class='mostrarin'></button><input type='text' name='nombreanun' placeholder='ingrese el nombre del anuncio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='srcanun' placeholder='ingrese el src del anuncio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='empresaanun' placeholder='ingrese la empresa del anuncio' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><input type='text' name='direccionanun' placeholder='ingrese la direccion' align='center' class='textin' required><button class='mostrarin'></button><br><button class='mostrarin'></button><br><input type='submit' class='iniciaranun' value='registrar' name='registraranun'><input type='reset' class='resetanun'></form><br>&nbsp;</td></tr></table>";
            }
        </script>
    </body>
</html>
